[project]
name = "python-foundations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mypy>=1.19.1",
    "numpy>=2.4.0",
    "pandas>=2.3.3",
]

[dependency-groups]
dev = [
    "ruff>=0.14.10",
]
